FROM golang:1.20-alpine AS builder

RUN apk add --no-cache git

WORKDIR /go/src/api-gateway/

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o /go/bin/api-gateway

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /api-gateway

COPY --from=builder /go/bin/api-gateway .

ENTRYPOINT ["./api-gateway"]