FROM golang:1.20-alpine AS builder

RUN apk add --no-cache git

WORKDIR /go/src/export-consumer/

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o /go/bin/export-consumer

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /export-consumer

COPY --from=builder /go/bin/export-consumer .

ENTRYPOINT ["./export-consumer"]